import nupogodi;
var i;
var ret;
var o=TNuPogodi();

PrintLN(o.user+":"+o.pass+"@"+o.host+":"+o.port);

o.host="127.0.0.1";
o.exch="ex1";

PrintLN(o.user+":"+o.pass+"@"+o.host+":"+o.port);

ret=o.ReadMessage("tu1");
if (ret)
    PrintLN("OK " + ret);
    if (o.ContentType != null)
        PrintLN("Content-type " + o.ContentType);
    else
        PrintLN("NO Content-type");
    end;
    if (o.ReplyTo != null)
        PrintLN("Reply-to " + o.ReplyTo);
    else
        PrintLN("NO Reply-to");
    end;
else
    PrintLN("ERR "+ o.error);
end;
                         