import nupogodi;
var i;
var ret;
var o=TNuPogodi();

PrintLN(o.user+":"+o.pass+"@"+o.host+":"+o.port);

o.host="127.0.0.1";
o.exch="ex1";

PrintLN(o.user+":"+o.pass+"@"+o.host+":"+o.port);

o.AddHeader("custom-header-1", "custom header 1 value");
o.AddHeader("custom-header-2", "custom header 2 value");

PrintLN("Headers: " + o.GetHeadersCount());

ret=o.SendText("Привет, мир "+String(i:o:4));
if (ret)
    PrintLN(ret);
else
    PrintLN(o.error);

end;
                         