import nupogodi;
import doctor; 

var i;
var ret;
var t;
var o=TNuPogodi();

PrintLN(o.user+":"+o.pass+"@"+o.host+":"+o.port);

o.host="127.0.0.1";
o.exch="ex1";

PrintLN(o.user+":"+o.pass+"@"+o.host+":"+o.port);

t = dcGetCurrentTime();

ret=o.ReadMessage("tu1");

PrintLN(String(dcGetCurrentTime() - t) + " ms");
if (ret)
    PrintLN("OK " + ret);
else
    PrintLN("ERR "+ o.error);
end;
                         