import nupogodi;
var i;
var N = 100000;
var ret;
var o=TNuPogodi();

o.host="127.0.0.1";
o.exch="ex1";

PrintLN(o.user+":"+o.pass+"@"+o.host+":"+o.port);

InitProgress(N);
for (i,1,N,1)

    ret=o.SendText("Привет, мир "+String(i:o:10), "key.file."+String(i:o:10));
    if (ret)
        PrintLN(ret);
    else
        PrintLN(o.error);

    end;

    UseProgress(i);

end;
RemProgress();                         